### ISSUE TITLE
cascadia fails on multiple attribute selector

### ISSUE THREAD

**Issue by suntong** [andybalholm/cascadia#24]
The multiple CSS attribute selectors like `input[name=Sex][value=M]` are valid selectors (for htmls like `<input type="radio" name="Sex" value="F" />` etc), as per [this](http://stackoverflow.com/questions/12340737/css-multiple-attribute-selector) and [this](http://www.w3.org/TR/CSS2/selector.html#attribute-selectors), however cascadia are failing on them:

```
panic: expected identifier, found 1 instead

goroutine 1 [running]:
panic(0x749a80, 0xc420075ec0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/andybalholm/cascadia.MustCompile(0x7ffe2d3262ea, 0x1b, 0x0)
        /export/repo/go-arch/src/github.com/andybalholm/cascadia/selector.go:59 +0x7e
...
```

Would you double-check please? Thx.

**Comment by suntong** [comment]
Not true. 

Close it now until I can figure it out exactly what happened...
